# Generated by Django 3.1.5 on 2021-04-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210425_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='diplay_picture',
            new_name='display_picture',
        ),
    ]
