# Generated by Django 3.1.5 on 2021-08-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='full_name',
            field=models.CharField(default='super user', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(default='super', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='mayank', max_length=30),
            preserve_default=False,
        ),
    ]
