# Generated by Django 3.1.5 on 2021-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210809_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
