# Generated by Django 3.1.5 on 2021-09-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userdetails_is_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='display_picture',
            field=models.ImageField(default='../avatardefault.png', upload_to=''),
        ),
    ]
